name: Deploy

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
        command: |
          cd ~/polygen
          /usr/bin/git pull
          ~/.cargo/bin/cargo build --release