name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Deploy
      uses: cross-the-world/scp-pipeline@master
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASS }}
        connect_timeout: 10s
        local: './*'
        remote: ~/polygen
      
    - name: Execute
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        script: |
          cd ~/polygen
          cargo build --release
          screen -S polygen -X quit
          screen -S polygen
          sudo target/release/polygen
          